### ISSUE TITLE
Jupyter instructions are not cross-OS

### ISSUE THREAD

**Issue by wood-chris** [EPCCed/cirrus-docs#138]
I think my instructions at https://github.com/EPCCed/cirrus-docs/pull/136 are OS specific, these exact instructions only seem to work for Macs. I'm working out the best cross-OS instructions...

**Comment by mbareford** [comment]
@wood-chris Can this issue be closed? I see that it's from Nov 2020.

**Comment by wood-chris** [comment]
@mbareford I'm not sure if the current instructions work for Windows - can someone from CSE test them?

**Comment by mbareford** [comment]
Windows instructions work as described.
