### ISSUE TITLE
Using Python: custom Anaconda environments

### ISSUE THREAD

**Issue by akrause2014** [EPCCed/cirrus-docs#140]
The documentation for creating custom environment for Python tells me to install miniconda and then create an environment. However, I can create an anaconda environment with the Python version and packages I wish to install, for example
```
module load anaconda/python3
conda create --name myenv python=3.8 jupyter
source activate myenv
```
This allows me to install other packages into my user environment just as when using miniconda. Shouldn't this be mentioned in the docs?
If this is not the recommended method it could explain why.

**Comment by mbareford** [comment]
The reason that the docs refer to miniconda rather than anaconda is that the former distribution is the more lightweight of the two, see https://stackoverflow.com/questions/45421163/anaconda-vs-miniconda .
With Custom environments based on miniconda it's easier to avoid having redundant packages.

**Comment by mbareford** [comment]
Sorry, just checked the date when this issue was raised and I see that it's quite old.
@akrause2014 Can this issue be closed?
