### ISSUE TITLE
Add OpenMPI documentation

### ISSUE THREAD

**Issue by juanfrh** [EPCCed/cirrus-docs#166]
[Application Developement Environment](https://docs.cirrus.ac.uk/user-guide/development/) contains a section called [Using HPE MPT](https://docs.cirrus.ac.uk/user-guide/development/#using-hpe-mpt), and [Using Intel MPI](https://docs.cirrus.ac.uk/user-guide/development/#using-intel-mpi). There's no section on "Using OpenMPI". If OpenMPI is only used for GPU codes, it might be not necessary. Nevertheless, I'd add a link to [Using the Cirrus GPU Nodes](https://docs.cirrus.ac.uk/user-guide/gpu/) as that section also contains some info on how to compile (GPU) codes.

**Comment by mbareford** [comment]
What sort of info re OpenMPI is required?

For example, there's a section on CUDA-aware MPI.
https://docs.cirrus.ac.uk/user-guide/gpu/#compiling-and-using-gpu-aware-mpi

**Comment by juanfrh** [comment]
I've updated the description to make the issue clearer.
