### ISSUE TITLE
MATLAB

### ISSUE THREAD

**Issue by mbareford** [EPCCed/cirrus-docs#197]
The MATLAB page needs updating as the 2018 version is no longer available on Cirrus.
Latest version on Cirrus is now R2021b and the default version is R2020b.

**Comment by juanfrh** [comment]
@aturner-epcc I think @RuiApostolo did some cleaning last Friday. I'd ask Rui what versions are available.

**Comment by RuiApostolo** [comment]
Correct, 2018a and 2018b modules got removed, and installations of those two plus 2019a/2019b/2019b_v2 were archived

**Comment by aturner-epcc** [comment]
Docs fixed
