### ISSUE TITLE
Reservation QoS

### ISSUE THREAD

**Issue by juanfrh** [EPCCed/cirrus-docs#223]
The [Running jobs on Cirrus](https://cirrus.readthedocs.io/en/main/user-guide/batch.html#reservations) section says:
> To submit jobs to a reservation, you need to add `--reservation=<reservation ID>` and `--qos=reservation` options to your job submission script or Slurm job submission command.

But `--qos=reservation` is not needed, otherwise the job submission script fails.
```
sbatch: error: Batch job submission failed: Invalid qos specification
```

**Comment by aturner-epcc** [comment]
@juanfrh Not quite sure what you mean here. Do you mean that adding `--qos=reservation` gives the error or you see the error if you do not add this option?

**Comment by juanfrh** [comment]
Adding `--qos=reservation` gives the error, but I don't know if this behaviour has changed since I submitted the issue. I'll do a test and let you know.

**Comment by juanfrh** [comment]
@lucaparisi91 helped me with the testing and this is no longer an issue.
