### ISSUE TITLE
Unordered HTML lists do not work

### ISSUE THREAD

**Issue by juanfrh** [EPCCed/cirrus-docs#232]
For instance, see:
https://cirrus.readthedocs.io/en/main/user-guide/data.html

The following list:
- Home file system
- Work file systems
- Solid state storage

doesn't appear well formatted.

**Comment by RuiApostolo** [comment]
Isn't the syntax of reST asterisks instead of dashes for unordered lists?

**Comment by juanfrh** [comment]
> Isn't the syntax of reST asterisks instead of dashes for unordered lists?

Well spotted, you're right, @RuiApostolo

**Comment by clairbarrass** [comment]
No longer relevant as moved to MKdocs and this was a ReadTheDocs issue
