### ISSUE TITLE
About linux distribution on Cirrus

### ISSUE THREAD

**Issue by Zihe33Huang** [EPCCed/cirrus-docs#262]
Hello, I noticed that at "https://www.cirrus.ac.uk/about",  it says "The HPC system runs the CentOS Linux distribution", but on the Cirrus using "cat /etc/os-release", the system version is RHEL8.4, is it because the information on the website is not updated?

**Comment by aturner-epcc** [comment]
Thanks for spotting this, it as now been fixed
