### ISSUE TITLE
Add link to external OpenFoam documentation.

### ISSUE THREAD

**Issue by marioa** [EPCCed/cirrus-docs#55]
It would be useful if, from the OpenFoam Cirrus page (http://cirrus.readthedocs.io/en/latest/software-packages/openfoam.html#using-openfoam-on-cirrus), you could point to the external OpenFoam documentation (as there are various forks of OpenFoam it would be good if you pointed to the correct documentation which I think is https://www.openfoam.com/documentation.

**Comment by aturner-epcc** [comment]
@marioa Thanks for the suggestion, this has been added.
