### ISSUE TITLE
Large data transfer guide AWOL

### ISSUE THREAD

**Issue by clairbarrass** [EPCCed/cirrus-docs#95]
In the Cirrus Data transfer guide, Before you start
https://cirrus.readthedocs.io/en/master/user-guide/transfer.html#before-you-start
there is the suggestion to read Harry Mangalam's guide at
http://moo.nac.uci.edu/~hjm/HOWTO_move_data.html
however, I am unable to load that page

**Comment by aturner-epcc** [comment]
Well spotted. It is still up at a different URL: https://hjmangalam.wordpress.com/2009/09/14/how-to-transfer-large-amounts-of-data-via-network/ I will correct the page.

**Comment by aturner-epcc** [comment]
Fixed in https://github.com/EPCCed/cirrus-docs/commit/d36ab9d80e8c31f48d3aa34175a43cd9667020b0
