### ISSUE TITLE
Gromacs GPU build

### ISSUE THREAD

**Issue by kevinstratford** [EPCCed/cirrus-docs#96]
Unintentionally, I pushed some changes to the

software-packages/gromacs.rst

page straight into the repository with a PR.

There are two new modules

gromacs/2020
gromacs-gpu/2020

The first is described by the existing stuff; the second is the GPU build which has a new section.

Let me know if you have any suggestions for improvements to this.

**Comment by aturner-epcc** [comment]
@kevinstratford Documentation looks fine to me I will close this issue. Thanks for the heads-up.
